name: Terraform

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  terraform-actions:
    name: Workflow
    runs-on: ubuntu-latest
    steps:

    - name: Checkout Repository
      uses: actions/checkout@master

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 0.14.6

    - name: Terraform Fmt
      id: fmt
      run: terraform fmt -check -diff
      continue-on-error: true

    - name: Terraform Init
      id: init
      run: terraform init
      continue-on-error: true

    - name: Terraform Validate
      id: validate
      run: terraform validate -no-color
      continue-on-error: true

    - name: Terraform Plan
      id: plan
      run: terraform plan -no-color
      continue-on-error: true

    - name: Comment on PR
      uses: actions/github-script@0.9.0
      if: github.event_name == 'pull_request'
      env:
        format_out: ${{ steps.fmt.outputs.stdout }}
        format_err: ${{ steps.fmt.outputs.stderr }}
        init_out: ${{ steps.init.outputs.stdout }}
        init_err: ${{ steps.init.outputs.stderr }}
        validate_out: ${{ steps.validate.outputs.stdout }}
        validate_err: ${{ steps.validate.outputs.stderr }}
        plan: "${{ steps.plan.outputs.stdout }}"
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const CODE_BLOCK = '```';
          const output = `
          ### Terraform Format and Style 🎨: \`${{ steps.fmt.outcome }}\`
          <details><summary>Logs</summary>
            <details><summary>Output</summary>
            ${ CODE_BLOCK }
            # terraform fmt
            ${ process.env.format_out }
            ${ CODE_BLOCK }
            </details>

            <details><summary>Errors</summary>
            ${ CODE_BLOCK }
            # terraform fmt
            ${ process.env.format_err }
            ${ CODE_BLOCK }
            </details>
          </details> <!-- End Format Logs -->

          ### Terraform Initialization ⚙️:  \`${{ steps.init.outcome }}\`
          <details><summary>Logs</summary>
            <details><summary>Output</summary>
            ${ CODE_BLOCK }
            # terraform init
            ${ process.env.init_out }
            ${ CODE_BLOCK }
            </details>

            <details><summary>Errors</summary>
            ${ CODE_BLOCK }
            # terraform init
            ${ process.env.init_err }
            ${ CODE_BLOCK }
            </details>
          </details> <!-- End Init Logs -->

          ### Terraform Validation 🤖: \`${{ steps.validate.outcome }}\`
          <details><summary>Logs</summary>
            <details><summary>Output</summary>
            ${ CODE_BLOCK }
            # terraform validate
            ${ process.env.validate_out }
            ${ CODE_BLOCK }
            </details>

            <details><summary>Errors</summary>
            ${ CODE_BLOCK }
            # terraform validate
            ${ process.env.validate_err }
            ${ CODE_BLOCK }
            </details>
          </details> <!-- End Validate Logs -->

          ### Terraform Plan 📖: \`${{ steps.plan.outcome }}\`
          <details><summary>Logs</summary>
          ${ CODE_BLOCK }terraform
          # terraform plan
          ${ process.env.plan }
          ${ CODE_BLOCK }
          </details>

          *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`, Working Directory: \`${{ env.tf_actions_working_dir }}\`, Workflow: \`${{ github.workflow }}\`*`;

          github.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: output
          })

    - name: 'End results'
      shell: bash
      run: |
        echo fmt
        test ${{ steps.fmt.outputs.exitcode }} -eq 0
        echo init
        test ${{ steps.init.outputs.exitcode }} -eq 0
        echo validate
        test ${{ steps.validate.outputs.exitcode }} -eq 0
